// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.OvulationCalculator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("last_period")]
        public DateTimeOffset LastPeriod { get; set; }

        [JsonProperty("cycle_length")]
        public long CycleLength { get; set; }

        [JsonProperty("ovulation")]
        public NextPeriod Ovulation { get; set; }

        [JsonProperty("fertile_window")]
        public FertileWindow FertileWindow { get; set; }

        [JsonProperty("most_fertile_days")]
        public FertileWindow MostFertileDays { get; set; }

        [JsonProperty("fertile_days")]
        public FertileDay[] FertileDays { get; set; }

        [JsonProperty("next_period")]
        public NextPeriod NextPeriod { get; set; }

        [JsonProperty("cycle_phases")]
        public CyclePhases CyclePhases { get; set; }

        [JsonProperty("current_status")]
        public CurrentStatus CurrentStatus { get; set; }

        [JsonProperty("disclaimer")]
        public string Disclaimer { get; set; }
    }

    public partial class CurrentStatus
    {
        [JsonProperty("current_phase")]
        public string CurrentPhase { get; set; }

        [JsonProperty("is_fertile")]
        public bool IsFertile { get; set; }

        [JsonProperty("days_until_ovulation")]
        public long DaysUntilOvulation { get; set; }

        [JsonProperty("days_until_next_period")]
        public long DaysUntilNextPeriod { get; set; }
    }

    public partial class CyclePhases
    {
        [JsonProperty("follicular_phase")]
        public FollicularPhase FollicularPhase { get; set; }

        [JsonProperty("ovulation")]
        public FollicularPhase Ovulation { get; set; }

        [JsonProperty("luteal_phase")]
        public FollicularPhase LutealPhase { get; set; }
    }

    public partial class FollicularPhase
    {
        [JsonProperty("duration_days")]
        public long DurationDays { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }
    }

    public partial class FertileDay
    {
        [JsonProperty("date")]
        public DateTimeOffset Date { get; set; }

        [JsonProperty("day_relative_to_ovulation")]
        public long DayRelativeToOvulation { get; set; }

        [JsonProperty("fertility_level")]
        public string FertilityLevel { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }
    }

    public partial class FertileWindow
    {
        [JsonProperty("start")]
        public DateTimeOffset Start { get; set; }

        [JsonProperty("end")]
        public DateTimeOffset End { get; set; }

        [JsonProperty("duration_days")]
        public long DurationDays { get; set; }
    }

    public partial class NextPeriod
    {
        [JsonProperty("date")]
        public DateTimeOffset Date { get; set; }

        [JsonProperty("days_from_last_period")]
        public long DaysFromLastPeriod { get; set; }
    }
}
